//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(intFacet))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(numFacet))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(noFixedFacet))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(enumerationType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://zigbee.org/zcl/types")]
[System.Xml.Serialization.XmlRootAttribute("minExclusive", Namespace="http://zigbee.org/zcl/types", IsNullable=false)]
public partial class facet : abstractFacet {
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(facet))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(intFacet))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(numFacet))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(noFixedFacet))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(enumerationType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://zigbee.org/zcl/types")]
public partial class abstractFacet {
    
    private string valueField;
    
    private bool fixedField;
    
    private string nameField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    public abstractFacet() {
        this.fixedField = false;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool @fixed {
        get {
            return this.fixedField;
        }
        set {
            this.fixedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr {
        get {
            return this.anyAttrField;
        }
        set {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="CommandFieldList", Namespace="http://zigbee.org/zcl/types")]
public partial class CommandFieldList1 {
    
    private CommandField[] fieldField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("field", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public CommandField[] field {
        get {
            return this.fieldField;
        }
        set {
            this.fieldField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://zigbee.org/zcl/types")]
public partial class CommandField {
    
    private object itemField;
    
    private string nameField;
    
    private string typeField;
    
    private bool arrayField;
    
    private byte arrayLengthSizeField;
    
    private string presentIfField;
    
    public CommandField() {
        this.arrayField = false;
        this.arrayLengthSizeField = ((byte)(1));
        this.presentIfField = "true";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("bitmap", typeof(BitmapDefinition1), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlElementAttribute("restriction", typeof(restrictionType1), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool array {
        get {
            return this.arrayField;
        }
        set {
            this.arrayField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(typeof(byte), "1")]
    public byte arrayLengthSize {
        get {
            return this.arrayLengthSizeField;
        }
        set {
            this.arrayLengthSizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("true")]
    public string presentIf {
        get {
            return this.presentIfField;
        }
        set {
            this.presentIfField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="BitmapDefinition", Namespace="http://zigbee.org/zcl/types")]
public partial class BitmapDefinition1 {
    
    private BitmapField[] elementField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("element", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public BitmapField[] element {
        get {
            return this.elementField;
        }
        set {
            this.elementField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://zigbee.org/zcl/types")]
public partial class BitmapField {
    
    private object[] restrictionField;
    
    private string nameField;
    
    private string typeField;
    
    private byte[] maskField;
    
    private byte shiftRightField;
    
    public BitmapField() {
        this.shiftRightField = ((byte)(0));
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("facet", IsNullable=false)]
    public object[] restriction {
        get {
            return this.restrictionField;
        }
        set {
            this.restrictionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="hexBinary")]
    public byte[] mask {
        get {
            return this.maskField;
        }
        set {
            this.maskField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(typeof(byte), "0")]
    public byte shiftRight {
        get {
            return this.shiftRightField;
        }
        set {
            this.shiftRightField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="restrictionType", Namespace="http://zigbee.org/zcl/types")]
public partial class restrictionType1 {
    
    private object[] itemsField;
    
    private ItemsChoiceType1[] itemsElementNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("enumeration", typeof(enumerationType))]
    [System.Xml.Serialization.XmlElementAttribute("fractionDigits", typeof(numFacet))]
    [System.Xml.Serialization.XmlElementAttribute("length", typeof(numFacet))]
    [System.Xml.Serialization.XmlElementAttribute("maxExclusive", typeof(facet))]
    [System.Xml.Serialization.XmlElementAttribute("maxInclusive", typeof(facet))]
    [System.Xml.Serialization.XmlElementAttribute("maxLength", typeof(numFacet))]
    [System.Xml.Serialization.XmlElementAttribute("minExclusive", typeof(facet))]
    [System.Xml.Serialization.XmlElementAttribute("minInclusive", typeof(facet))]
    [System.Xml.Serialization.XmlElementAttribute("minLength", typeof(numFacet))]
    [System.Xml.Serialization.XmlElementAttribute("pattern", typeof(pattern))]
    [System.Xml.Serialization.XmlElementAttribute("sequence", typeof(restrictionTypeFacetSequence))]
    [System.Xml.Serialization.XmlElementAttribute("totalDigits", typeof(totalDigits))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType1[] ItemsElementName {
        get {
            return this.itemsElementNameField;
        }
        set {
            this.itemsElementNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://zigbee.org/zcl/types")]
[System.Xml.Serialization.XmlRootAttribute("enumeration", Namespace="http://zigbee.org/zcl/types", IsNullable=false)]
public partial class enumerationType : noFixedFacet {
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(enumerationType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://zigbee.org/zcl/types")]
public partial class noFixedFacet : facet {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://zigbee.org/zcl/types")]
[System.Xml.Serialization.XmlRootAttribute("fractionDigits", Namespace="http://zigbee.org/zcl/types", IsNullable=false)]
public partial class numFacet : facet {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://zigbee.org/zcl/types")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://zigbee.org/zcl/types", IsNullable=false)]
public partial class pattern : noFixedFacet {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://zigbee.org/zcl/types")]
[System.Xml.Serialization.XmlRootAttribute("sequence", Namespace="http://zigbee.org/zcl/types", IsNullable=false)]
public partial class restrictionTypeFacetSequence : CommandFieldList {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://zigbee.org/zcl/types")]
public partial class CommandFieldList {
    
    private CommandField[] fieldField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("field", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public CommandField[] field {
        get {
            return this.fieldField;
        }
        set {
            this.fieldField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://zigbee.org/zcl/types")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://zigbee.org/zcl/types", IsNullable=false)]
public partial class totalDigits : numFacet {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://zigbee.org/zcl/types", IncludeInSchema=false)]
public enum ItemsChoiceType1 {
    
    /// <remarks/>
    enumeration,
    
    /// <remarks/>
    fractionDigits,
    
    /// <remarks/>
    length,
    
    /// <remarks/>
    maxExclusive,
    
    /// <remarks/>
    maxInclusive,
    
    /// <remarks/>
    maxLength,
    
    /// <remarks/>
    minExclusive,
    
    /// <remarks/>
    minInclusive,
    
    /// <remarks/>
    minLength,
    
    /// <remarks/>
    pattern,
    
    /// <remarks/>
    sequence,
    
    /// <remarks/>
    totalDigits,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://zigbee.org/zcl/clusters")]
public partial class ClusterType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://zigbee.org/zcl/clusters")]
public partial class Tag {
    
    private uint idField;
    
    private string nameField;
    
    private string typeField;
    
    private bool requiredField;
    
    public Tag() {
        this.requiredField = false;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool required {
        get {
            return this.requiredField;
        }
        set {
            this.requiredField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://zigbee.org/zcl/clusters")]
public partial class ClusterSide {
    
    private Attribute[] attributesField;
    
    private Command[] commandsField;
    
    private string baseField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("attribute", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public Attribute[] attributes {
        get {
            return this.attributesField;
        }
        set {
            this.attributesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("command", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public Command[] commands {
        get {
            return this.commandsField;
        }
        set {
            this.commandsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace")]
    public string @base {
        get {
            return this.baseField;
        }
        set {
            this.baseField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://zigbee.org/zcl/clusters")]
public partial class Attribute {
    
    private object itemField;
    
    private byte[] idField;
    
    private string nameField;
    
    private string typeField;
    
    private bool readableField;
    
    private bool writableField;
    
    private bool writeOptionalField;
    
    private bool reportRequiredField;
    
    private bool sceneRequiredField;
    
    private bool requiredField;
    
    private string minField;
    
    private string maxField;
    
    private string defaultField;
    
    public Attribute() {
        this.readableField = true;
        this.writableField = false;
        this.writeOptionalField = false;
        this.reportRequiredField = false;
        this.sceneRequiredField = false;
        this.requiredField = false;
        this.minField = "0";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("bitmap", typeof(BitmapDefinition), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlElementAttribute("restriction", typeof(restrictionType), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="hexBinary")]
    public byte[] id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(true)]
    public bool readable {
        get {
            return this.readableField;
        }
        set {
            this.readableField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool writable {
        get {
            return this.writableField;
        }
        set {
            this.writableField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool writeOptional {
        get {
            return this.writeOptionalField;
        }
        set {
            this.writeOptionalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool reportRequired {
        get {
            return this.reportRequiredField;
        }
        set {
            this.reportRequiredField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool sceneRequired {
        get {
            return this.sceneRequiredField;
        }
        set {
            this.sceneRequiredField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool required {
        get {
            return this.requiredField;
        }
        set {
            this.requiredField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    [System.ComponentModel.DefaultValueAttribute("0")]
    public string min {
        get {
            return this.minField;
        }
        set {
            this.minField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string max {
        get {
            return this.maxField;
        }
        set {
            this.maxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string @default {
        get {
            return this.defaultField;
        }
        set {
            this.defaultField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://zigbee.org/zcl/types")]
public partial class BitmapDefinition {
    
    private BitmapField[] elementField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("element", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public BitmapField[] element {
        get {
            return this.elementField;
        }
        set {
            this.elementField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://zigbee.org/zcl/types")]
public partial class restrictionType {
    
    private object[] itemsField;
    
    private ItemsChoiceType[] itemsElementNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("enumeration", typeof(enumerationType))]
    [System.Xml.Serialization.XmlElementAttribute("fractionDigits", typeof(numFacet))]
    [System.Xml.Serialization.XmlElementAttribute("length", typeof(numFacet))]
    [System.Xml.Serialization.XmlElementAttribute("maxExclusive", typeof(facet))]
    [System.Xml.Serialization.XmlElementAttribute("maxInclusive", typeof(facet))]
    [System.Xml.Serialization.XmlElementAttribute("maxLength", typeof(numFacet))]
    [System.Xml.Serialization.XmlElementAttribute("minExclusive", typeof(facet))]
    [System.Xml.Serialization.XmlElementAttribute("minInclusive", typeof(facet))]
    [System.Xml.Serialization.XmlElementAttribute("minLength", typeof(numFacet))]
    [System.Xml.Serialization.XmlElementAttribute("pattern", typeof(pattern))]
    [System.Xml.Serialization.XmlElementAttribute("sequence", typeof(restrictionTypeFacetSequence))]
    [System.Xml.Serialization.XmlElementAttribute("totalDigits", typeof(totalDigits))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType[] ItemsElementName {
        get {
            return this.itemsElementNameField;
        }
        set {
            this.itemsElementNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://zigbee.org/zcl/types", IncludeInSchema=false)]
public enum ItemsChoiceType {
    
    /// <remarks/>
    enumeration,
    
    /// <remarks/>
    fractionDigits,
    
    /// <remarks/>
    length,
    
    /// <remarks/>
    maxExclusive,
    
    /// <remarks/>
    maxInclusive,
    
    /// <remarks/>
    maxLength,
    
    /// <remarks/>
    minExclusive,
    
    /// <remarks/>
    minInclusive,
    
    /// <remarks/>
    minLength,
    
    /// <remarks/>
    pattern,
    
    /// <remarks/>
    sequence,
    
    /// <remarks/>
    totalDigits,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://zigbee.org/zcl/clusters")]
public partial class Command {
    
    private CommandField[] fieldsField;
    
    private TagRef[] tagField;
    
    private byte[] idField;
    
    private string nameField;
    
    private bool requiredField;
    
    public Command() {
        this.requiredField = false;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("field", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public CommandField[] fields {
        get {
            return this.fieldsField;
        }
        set {
            this.fieldsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("tag", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public TagRef[] tag {
        get {
            return this.tagField;
        }
        set {
            this.tagField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="hexBinary")]
    public byte[] id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool required {
        get {
            return this.requiredField;
        }
        set {
            this.requiredField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://zigbee.org/zcl/clusters")]
public partial class TagRef {
    
    private uint refField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint @ref {
        get {
            return this.refField;
        }
        set {
            this.refField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://zigbee.org/zcl/clusters")]
public partial class Classification {
    
    private string hierarchyField;
    
    private byte[] baseField;
    
    private ClusterRole roleField;
    
    private string picsCodeField;
    
    private byte primaryTransactionField;
    
    public Classification() {
        this.primaryTransactionField = ((byte)(1));
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string hierarchy {
        get {
            return this.hierarchyField;
        }
        set {
            this.hierarchyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="hexBinary")]
    public byte[] @base {
        get {
            return this.baseField;
        }
        set {
            this.baseField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ClusterRole role {
        get {
            return this.roleField;
        }
        set {
            this.roleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string picsCode {
        get {
            return this.picsCodeField;
        }
        set {
            this.picsCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(typeof(byte), "1")]
    public byte primaryTransaction {
        get {
            return this.primaryTransactionField;
        }
        set {
            this.primaryTransactionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://zigbee.org/zcl/clusters")]
public enum ClusterRole {
    
    /// <remarks/>
    application,
    
    /// <remarks/>
    utility,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://zigbee.org/zcl/types")]
public partial class intFacet : facet {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://zigbee.org/zcl/types")]
[System.Xml.Serialization.XmlRootAttribute("type", Namespace="http://zigbee.org/zcl/types", IsNullable=false)]
public partial class ZigbeeDataType {
    
    private object[] restrictionField;
    
    private byte[] idField;
    
    private string nameField;
    
    private string shortField;
    
    private bool discreteField;
    
    private string inheritsFromField;
    
    public ZigbeeDataType() {
        this.discreteField = false;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("facet", IsNullable=false)]
    public object[] restriction {
        get {
            return this.restrictionField;
        }
        set {
            this.restrictionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="hexBinary")]
    public byte[] id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string @short {
        get {
            return this.shortField;
        }
        set {
            this.shortField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool discrete {
        get {
            return this.discreteField;
        }
        set {
            this.discreteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string inheritsFrom {
        get {
            return this.inheritsFromField;
        }
        set {
            this.inheritsFromField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://zigbee.org/zcl/clusters")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://zigbee.org/zcl/clusters", IsNullable=false)]
public partial class cluster {
    
    private Classification classificationField;
    
    private ZigbeeDataType[] typeField;
    
    private ClusterSide serverField;
    
    private ClusterSide clientField;
    
    private Tag[] tagsField;
    
    private byte[] idField;
    
    private ushort revisionField;
    
    private string nameField;
    
    private string baseField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public Classification classification {
        get {
            return this.classificationField;
        }
        set {
            this.classificationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("type", Namespace="http://zigbee.org/zcl/types")]
    public ZigbeeDataType[] type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ClusterSide server {
        get {
            return this.serverField;
        }
        set {
            this.serverField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ClusterSide client {
        get {
            return this.clientField;
        }
        set {
            this.clientField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("tag", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public Tag[] tags {
        get {
            return this.tagsField;
        }
        set {
            this.tagsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="hexBinary")]
    public byte[] id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort revision {
        get {
            return this.revisionField;
        }
        set {
            this.revisionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace")]
    public string @base {
        get {
            return this.baseField;
        }
        set {
            this.baseField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://zigbee.org/zcl/clusters")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://zigbee.org/zcl/clusters", IsNullable=false)]
public partial class global {
    
    private ZigbeeDataType[] typeField;
    
    private Attribute[] attributesField;
    
    private Command[] commandsField;
    
    private string baseField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("type", Namespace="http://zigbee.org/zcl/types")]
    public ZigbeeDataType[] type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("attribute", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public Attribute[] attributes {
        get {
            return this.attributesField;
        }
        set {
            this.attributesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("command", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public Command[] commands {
        get {
            return this.commandsField;
        }
        set {
            this.commandsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace")]
    public string @base {
        get {
            return this.baseField;
        }
        set {
            this.baseField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://zigbee.org/zcl/clusters")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://zigbee.org/zcl/clusters", IsNullable=false)]
public partial class library {
    
    private ZigbeeDataType[] typeField;
    
    private global globalField;
    
    private cluster[] clusterField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("type", Namespace="http://zigbee.org/zcl/types")]
    public ZigbeeDataType[] type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    public global global {
        get {
            return this.globalField;
        }
        set {
            this.globalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("cluster")]
    public cluster[] cluster {
        get {
            return this.clusterField;
        }
        set {
            this.clusterField = value;
        }
    }
}
